# Generated by Django 2.2 on 2019-04-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='time',
            field=models.TimeField(verbose_name='Billing Time'),
        ),
    ]
