# Generated by Django 2.2 on 2019-04-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20190404_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='time',
            field=models.DateTimeField(verbose_name='Billing Time'),
        ),
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
