# Generated by Django 2.2 on 2019-04-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20190404_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Billing Time'),
        ),
    ]
