# Generated by Django 2.2 on 2019-04-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_auto_20190405_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='meter_status',
            field=models.BooleanField(default=True),
        ),
    ]
